/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiFrameRouteImport } from './routes/api/frame'
import { Route as ApiPolicyRouteImport } from './routes/api/policy'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiWorkmapRouteImport } from './routes/api/workmap'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ApiDebriefGapsRouteImport } from './routes/api/debrief/gaps'
import { Route as ApiDebriefTeachbackRouteImport } from './routes/api/debrief/teachback'
import { Route as ApiElevenlabsScribeTokenRouteImport } from './routes/api/elevenlabs/scribe-token'
import { Route as ApiElevenlabsSignedUrlRouteImport } from './routes/api/elevenlabs/signed-url'
import { Route as ApiGuardrailsCompileRouteImport } from './routes/api/guardrails/compile'
import { Route as ApiHelpyTurnRouteImport } from './routes/api/helpy/turn'
import { Route as ProjectsProjectIdTasksTaskIdRouteImport } from './routes/projects.$projectId_.tasks.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFrameRoute = ApiFrameRouteImport.update({
  id: '/api/frame',
  path: '/api/frame',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolicyRoute = ApiPolicyRouteImport.update({
  id: '/api/policy',
  path: '/api/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkmapRoute = ApiWorkmapRouteImport.update({
  id: '/api/workmap',
  path: '/api/workmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebriefGapsRoute = ApiDebriefGapsRouteImport.update({
  id: '/api/debrief/gaps',
  path: '/api/debrief/gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebriefTeachbackRoute = ApiDebriefTeachbackRouteImport.update({
  id: '/api/debrief/teachback',
  path: '/api/debrief/teachback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElevenlabsScribeTokenRoute =
  ApiElevenlabsScribeTokenRouteImport.update({
    id: '/api/elevenlabs/scribe-token',
    path: '/api/elevenlabs/scribe-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiElevenlabsSignedUrlRoute = ApiElevenlabsSignedUrlRouteImport.update({
  id: '/api/elevenlabs/signed-url',
  path: '/api/elevenlabs/signed-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuardrailsCompileRoute = ApiGuardrailsCompileRouteImport.update({
  id: '/api/guardrails/compile',
  path: '/api/guardrails/compile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHelpyTurnRoute = ApiHelpyTurnRouteImport.update({
  id: '/api/helpy/turn',
  path: '/api/helpy/turn',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdTasksTaskIdRoute =
  ProjectsProjectIdTasksTaskIdRouteImport.update({
    id: '/projects/$projectId_/tasks/$taskId',
    path: '/projects/$projectId/tasks/$taskId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/frame': typeof ApiFrameRoute
  '/api/policy': typeof ApiPolicyRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/workmap': typeof ApiWorkmapRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/debrief/gaps': typeof ApiDebriefGapsRoute
  '/api/debrief/teachback': typeof ApiDebriefTeachbackRoute
  '/api/elevenlabs/scribe-token': typeof ApiElevenlabsScribeTokenRoute
  '/api/elevenlabs/signed-url': typeof ApiElevenlabsSignedUrlRoute
  '/api/guardrails/compile': typeof ApiGuardrailsCompileRoute
  '/api/helpy/turn': typeof ApiHelpyTurnRoute
  '/projects/$projectId/tasks/$taskId': typeof ProjectsProjectIdTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/frame': typeof ApiFrameRoute
  '/api/policy': typeof ApiPolicyRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/workmap': typeof ApiWorkmapRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/debrief/gaps': typeof ApiDebriefGapsRoute
  '/api/debrief/teachback': typeof ApiDebriefTeachbackRoute
  '/api/elevenlabs/scribe-token': typeof ApiElevenlabsScribeTokenRoute
  '/api/elevenlabs/signed-url': typeof ApiElevenlabsSignedUrlRoute
  '/api/guardrails/compile': typeof ApiGuardrailsCompileRoute
  '/api/helpy/turn': typeof ApiHelpyTurnRoute
  '/projects/$projectId/tasks/$taskId': typeof ProjectsProjectIdTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/frame': typeof ApiFrameRoute
  '/api/policy': typeof ApiPolicyRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/workmap': typeof ApiWorkmapRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/debrief/gaps': typeof ApiDebriefGapsRoute
  '/api/debrief/teachback': typeof ApiDebriefTeachbackRoute
  '/api/elevenlabs/scribe-token': typeof ApiElevenlabsScribeTokenRoute
  '/api/elevenlabs/signed-url': typeof ApiElevenlabsSignedUrlRoute
  '/api/guardrails/compile': typeof ApiGuardrailsCompileRoute
  '/api/helpy/turn': typeof ApiHelpyTurnRoute
  '/projects/$projectId_/tasks/$taskId': typeof ProjectsProjectIdTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/frame'
    | '/api/policy'
    | '/api/tts'
    | '/api/workmap'
    | '/projects/$projectId'
    | '/projects/'
    | '/api/debrief/gaps'
    | '/api/debrief/teachback'
    | '/api/elevenlabs/scribe-token'
    | '/api/elevenlabs/signed-url'
    | '/api/guardrails/compile'
    | '/api/helpy/turn'
    | '/projects/$projectId/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/frame'
    | '/api/policy'
    | '/api/tts'
    | '/api/workmap'
    | '/projects/$projectId'
    | '/projects'
    | '/api/debrief/gaps'
    | '/api/debrief/teachback'
    | '/api/elevenlabs/scribe-token'
    | '/api/elevenlabs/signed-url'
    | '/api/guardrails/compile'
    | '/api/helpy/turn'
    | '/projects/$projectId/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/api/frame'
    | '/api/policy'
    | '/api/tts'
    | '/api/workmap'
    | '/projects/$projectId'
    | '/projects/'
    | '/api/debrief/gaps'
    | '/api/debrief/teachback'
    | '/api/elevenlabs/scribe-token'
    | '/api/elevenlabs/signed-url'
    | '/api/guardrails/compile'
    | '/api/helpy/turn'
    | '/projects/$projectId_/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiFrameRoute: typeof ApiFrameRoute
  ApiPolicyRoute: typeof ApiPolicyRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiWorkmapRoute: typeof ApiWorkmapRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiDebriefGapsRoute: typeof ApiDebriefGapsRoute
  ApiDebriefTeachbackRoute: typeof ApiDebriefTeachbackRoute
  ApiElevenlabsScribeTokenRoute: typeof ApiElevenlabsScribeTokenRoute
  ApiElevenlabsSignedUrlRoute: typeof ApiElevenlabsSignedUrlRoute
  ApiGuardrailsCompileRoute: typeof ApiGuardrailsCompileRoute
  ApiHelpyTurnRoute: typeof ApiHelpyTurnRoute
  ProjectsProjectIdTasksTaskIdRoute: typeof ProjectsProjectIdTasksTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/frame': {
      id: '/api/frame'
      path: '/api/frame'
      fullPath: '/api/frame'
      preLoaderRoute: typeof ApiFrameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/policy': {
      id: '/api/policy'
      path: '/api/policy'
      fullPath: '/api/policy'
      preLoaderRoute: typeof ApiPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workmap': {
      id: '/api/workmap'
      path: '/api/workmap'
      fullPath: '/api/workmap'
      preLoaderRoute: typeof ApiWorkmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debrief/gaps': {
      id: '/api/debrief/gaps'
      path: '/api/debrief/gaps'
      fullPath: '/api/debrief/gaps'
      preLoaderRoute: typeof ApiDebriefGapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debrief/teachback': {
      id: '/api/debrief/teachback'
      path: '/api/debrief/teachback'
      fullPath: '/api/debrief/teachback'
      preLoaderRoute: typeof ApiDebriefTeachbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elevenlabs/scribe-token': {
      id: '/api/elevenlabs/scribe-token'
      path: '/api/elevenlabs/scribe-token'
      fullPath: '/api/elevenlabs/scribe-token'
      preLoaderRoute: typeof ApiElevenlabsScribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elevenlabs/signed-url': {
      id: '/api/elevenlabs/signed-url'
      path: '/api/elevenlabs/signed-url'
      fullPath: '/api/elevenlabs/signed-url'
      preLoaderRoute: typeof ApiElevenlabsSignedUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guardrails/compile': {
      id: '/api/guardrails/compile'
      path: '/api/guardrails/compile'
      fullPath: '/api/guardrails/compile'
      preLoaderRoute: typeof ApiGuardrailsCompileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/helpy/turn': {
      id: '/api/helpy/turn'
      path: '/api/helpy/turn'
      fullPath: '/api/helpy/turn'
      preLoaderRoute: typeof ApiHelpyTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId_/tasks/$taskId': {
      id: '/projects/$projectId_/tasks/$taskId'
      path: '/projects/$projectId/tasks/$taskId'
      fullPath: '/projects/$projectId/tasks/$taskId'
      preLoaderRoute: typeof ProjectsProjectIdTasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiFrameRoute: ApiFrameRoute,
  ApiPolicyRoute: ApiPolicyRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiWorkmapRoute: ApiWorkmapRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiDebriefGapsRoute: ApiDebriefGapsRoute,
  ApiDebriefTeachbackRoute: ApiDebriefTeachbackRoute,
  ApiElevenlabsScribeTokenRoute: ApiElevenlabsScribeTokenRoute,
  ApiElevenlabsSignedUrlRoute: ApiElevenlabsSignedUrlRoute,
  ApiGuardrailsCompileRoute: ApiGuardrailsCompileRoute,
  ApiHelpyTurnRoute: ApiHelpyTurnRoute,
  ProjectsProjectIdTasksTaskIdRoute: ProjectsProjectIdTasksTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
